# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('problem_statement', models.TextField()),
            ],
        ),
    ]
