# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[['py', 'Python 3'], ['cpp', 'C++']], default='py', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_of_submission',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
