# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0006_auto_20171106_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='timelimit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
