# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0007_problem_timelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='memlimit',
            field=models.IntegerField(default=256000),
            preserve_default=False,
        ),
    ]
