# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0009_auto_20171109_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='timelimit',
            field=models.IntegerField(default=1),
        ),
    ]
