# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0010_auto_20171109_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='no_of_cases',
            field=models.IntegerField(default=1),
        ),
    ]
