# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0014_auto_20171128_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('contest_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
