# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0015_auto_20171128_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contests',
            new_name='Contest',
        ),
    ]
