# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0017_problem_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_score',
            field=models.IntegerField(default=1),
        ),
    ]
