# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0019_leaderboardentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
