# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0020_auto_20171208_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinejudge.Contest'),
            preserve_default=False,
        ),
    ]
