# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0021_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='last_submission_time',
            field=models.DateTimeField(default=0),
        ),
    ]
