# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0024_auto_20171209_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='last_submission_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 9, 11, 4, 59, 195115, tzinfo=utc)),
        ),
    ]
