# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0026_auto_20171209_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='last_submission_time',
            field=models.DateTimeField(),
        ),
    ]
