# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0028_remove_leaderboardentry_last_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='last_submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
