# Generated by Django 2.0.2 on 2018-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0029_leaderboardentry_last_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='last_submission_time',
            field=models.DateTimeField(null=True),
        ),
    ]
