# Generated by Django 2.0.2 on 2018-02-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0030_auto_20180205_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
