# Generated by Django 2.0.2 on 2018-02-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0031_contest_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[['py', 'Python 3'], ['cpp', 'C++'], ['c', 'C'], ['java', 'Java']], default='py', max_length=20),
        ),
    ]
